version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sandbox-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6q770mk0e26o"
s3_prefix = "sandbox-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiStageName=\"Prod\" HelloWorldFunctionApiKeyValue=\"MD6Rz9lQLh2yUiAln0g384LkyoUebgWj5iRlE9wS\""

