AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sandbox-sam

  Sample SAM Template for sandbox-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ApiStageName:
    Type: String
    Default: Prod

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref HelloWorldFunctionApi
            Path: /hello
            Method: get

  HelloWorldFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      Auth:
        ApiKeyRequired: True
        ResourcePolicy:
          CustomStatements:
            Effect: Allow
            Principal: "*"
            Action: execute-api:Invoke
            Resource: execute-api:/*/*/*

  UsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      ApiStages:
        - ApiId: !Ref HelloWorldFunctionApi
          Stage: !Ref ApiStageName
    DependsOn:
      - HelloWorldFunctionApiStage

  UsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
    DependsOn:
      - UsagePlan
      - ApiKey

  ApiKey:
    Type: "AWS::ApiGateway::ApiKey"
    Properties:
      Enabled: True
      StageKeys:
        - RestApiId: !Ref HelloWorldFunctionApi
          StageName: !Ref ApiStageName
    DependsOn:
      - HelloWorldFunctionApiStage

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunctionApi:
    Description: "API Gateway endpoint URL for stage for Hello World function"
    Value: !Sub "https://${HelloWorldFunctionApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
